### ISSUE TITLE
Small change = Big help

### ISSUE THREAD

**Issue by nebojsa-simic** [parisholley/wordpress-fantastic-elasticsearch#116]
Hi, 

First of all big thank you for the plugin, it's really fantastic.
One small code change in the Indexer would help a lot.
If you could add a check in the method addOrUpdate after getting the $data from the _build_document:
```php
if (!empty($data)) {
           $type->addDocument(new \Elastica\Document($post->ID, $data));		
}
```

That would allow us to return an empty $document from the "elasticsearch_indexer_build_document" filter and exclude items from the index based on certain criteria (specific post_type, meta_value etc.)

**Comment by parisholley** [comment]
Add the change as a pull request, and I'll merge :)
