### ISSUE TITLE
Server URL (Malformed URL)

### ISSUE THREAD

**Issue by hoanhd** [parisholley/wordpress-fantastic-elasticsearch#120]
This is my server info :
Server URL : http://107.167.***.***:9200/
Index Name : search

When I click save button ,i got a message : Malformed URL

Tested it ok via chrome (http://107.167.***.***:9200/search) :
settings: {
index: {
creation_date: "1427362456824",
mapping: {
allow_type_wrapper: "true"
},
uuid: "-c9CTIpPRgi3KLpySNxUxQ",
number_of_replicas: "1",
number_of_shards: "5",
version: {
created: "1050099"
}
}
},

This is log:
Call to URLFetch failed with application error 1 for url 107.167.*.*search/_status

**Comment by parisholley** [comment]
Did you try without trailing slash?

**Comment by jackoggy** [comment]
how to get the server url information 
is it our server url or its elasticsearch server url
