### ISSUE TITLE
Blank Page Issue with V. 3.1.1 and WP 4.1.1

### ISSUE THREAD

**Issue by alexander9586** [parisholley/wordpress-fantastic-elasticsearch#121]
FantasticElasticSearch works for about 3 Months but now I get an blank page if I publish or update a posts / page.
If I deactivate the plugin everything works fine.
I deactivated all other plugins and only activate this plugin and it happen again.

**Comment by mikelking** [comment]
The first place I would look is in the PHP error log see if there are any fatal errors that would halt the page from loading. It's possible you are running a version of PHP that is not compatible with the plugin.

**Comment by alexander9586** [comment]
This is what I get:

Fatal error: Uncaught exception 'Elastica\Exception\Connection\HttpException' with message 'Operation timed out' in /var/www/vhosts/DOMAIN/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:154 Stack trace: #0 /var/www/vhosts/DOMAIN/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Request.php(168): Elastica\Transport\Http->exec(Object(Elastica\Request), Array) #1 /var/www/vhosts/DOMAIN/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Client.php(592): Elastica\Request->send() #2 /var/www/vhosts/DOMAIN/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Index.php(444): Elastica\Client->request('DOMAIN/po...', 'PUT', Array, Array) #3 /var/www/vhosts/DOMAIN/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Type.php(511): Elastica\Index->request('post/4308', 'PUT', Array, Array) #4 /var/www/vhosts/DOMAIN in /var/www/vhosts/DOMAIN/wp-content/plugins/fantastic-elasticsearch/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 154

**Comment by alexander9586** [comment]
Found out that my ElasticSearch Host was broken. Bug is fixed after switch to another one.
