### ISSUE TITLE
Wordpress Filters searcher_search missing argument

### ISSUE THREAD

**Issue by wkw** [parisholley/wordpress-fantastic-elasticsearch#123]
The [filters](https://github.com/parisholley/wordpress-fantastic-elasticsearch/wiki/Wordpress-Filters) wiki page for `searcher_search` is missing the $search arg.
[this line in src suggests...](https://github.com/parisholley/wordpress-fantastic-elasticsearch/blob/master/src/elasticsearch/Searcher.php#L61)
... it should be:
`elasticsearch_searcher_search (\Elastica\Search $search, \Elastica\Query $query)`

would have done pull req. but couldn't figure out how to do that for the wiki

**Comment by parisholley** [comment]
updated!
