### ISSUE TITLE
Sorting example code: "score" or "_score"?

### ISSUE THREAD

**Issue by wkw** [parisholley/wordpress-fantastic-elasticsearch#124]
the example code in wiki [How do I implement sorting?](https://github.com/parisholley/wordpress-fantastic-elasticsearch/wiki/How-do-I-implement-sorting%3F) was throwing errors. is the sort by "score" actually "_score"? changing to the latter got rid of my elastica exceptions.

**Comment by parisholley** [comment]
Updated, it appears _score is the correct field.
