### ISSUE TITLE
Plugin not working with Classipress theme

### ISSUE THREAD

**Issue by ajaymaravind** [parisholley/wordpress-fantastic-elasticsearch#129]
Search is not working with classipress theme. Using searchly as the server.

Site is indexed but search is not using elasticsearch.  Tested by checking order of search results and also searchly analytics. When 2015 theme is used, it works.

**Comment by parisholley** [comment]
unfortunately, you will need to debug this issue yourself. if you make any progress, feel free to fix in the project and issue a pull
