### ISSUE TITLE
Cant save server url http://localhost:9200/

### ISSUE THREAD

**Issue by webmatter** [parisholley/wordpress-fantastic-elasticsearch#131]
elasticsearch is installed on the server so server url settings should be localhost:9200 
If I enter server url http://localhost:9200/ it results in a blank page and the settings won't be saved.
Any tips are appreciated. Thanks.

**Comment by jackoggy** [comment]
how to get the server url

**Comment by parisholley** [comment]
try with the latest branch and let me know if it works for you, keeping in mind this plugin now only supports 2.x+

https://github.com/parisholley/wordpress-fantastic-elasticsearch/tree/upgrade
